### ISSUE TITLE
There is no implicit reference conversion from '...' to 'MediatR.INotification'

### ISSUE THREAD

**Issue by dradovic** [StevenRasmussen/MediatR.Dynamic#2]
Thanks for providing this useful package.

However, at the time I cannot use it because I get a compilation error on

    services.AddDynamicNotificationHandler<...>();

> The type '...' cannot be used as type parameter 'T' in the generic type or method 'MediatRDynamic.AddDynamicNotificationHandler<T>(IServiceCollection)'. There is no implicit reference conversion from '...' to 'MediatR.INotification'.

My assumption is that this is caused by the fact that I'm using the latest version of MediatR (10.0.1) which supports the `MediatR.Contracts` abstraction package where the `INotification` is sitting that I'm using for my notification.

I assume you should simply upgrade your project to MediatR 10.0.1 to support that.

**Comment by StevenRasmussen** [comment]
@dradovic - Thanks for pointing this out!  I have updated the project and released a new version to NuGet.  The new version is 10.0.0 to reflect that it uses MediatR v10.

**Comment by dradovic** [comment]
Wow, that was fast. I've upgraded and I can confirm that it works like a charm now. Thanks again.
